project_id = "rzkguvbdyaukfzgolpqi"

[functions.invite-user]
verify_jwt = false

[functions.remove-user]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[auth]
additional_redirect_urls = ["https://class-cash-tan.vercel.app/**", "http://localhost:8081/**"]
site_url = "https://class-cash-tan.vercel.app"

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.vector]
enabled = false
