// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxvknfipprlmoutzkbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneHZrbmZpcHBybG1vdXR6a2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjU4MjgsImV4cCI6MjA3MTMwMTgyOH0.0rVZedFEyGXRN774wJugi3dEq6JTvqg9qDLNdSzK_RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});